# 工作流名称（在 Actions 页面显示）
name: 自动构建并推送 Docker 镜像到 Docker Hub

# 触发条件：当代码推送到 main 分支时自动运行
on:
  push:
    branches: [ "main" ]  # 可改为你的主分支（如 master、dev）

# 定义要执行的任务
jobs:
  build-and-push:
    # 运行环境：使用 GitHub 提供的 Ubuntu 服务器
    runs-on: ubuntu-latest
    
    # 任务步骤
    steps:
      # 步骤 1：拉取 GitHub 仓库的代码到运行环境
      - name: 拉取当前仓库代码
        uses: actions/checkout@v4  # 调用官方动作，无需自己写代码
        
      # 步骤 2：设置 Docker 环境并登录 Docker Hub
      - name: 登录到 Docker Hub
        uses: docker/login-action@v3  # Docker 官方登录动作
        with:
          # 从仓库密钥中获取用户名和令牌（安全且不会暴露）
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          
      # 步骤 3：构建 Docker 镜像并推送到 Docker Hub
      - name: 构建并推送镜像
        uses: docker/build-push-action@v5  # Docker 官方构建+推送动作
        with:
          context: .  # 构建上下文（当前仓库根目录，即 Dockerfile 所在位置）
          push: true  # 允许推送镜像到 Docker Hub
          # 镜像标签格式：Docker用户名/仓库名:版本
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/bobojian:latest,${{ secrets.DOCKER_HUB_USERNAME }}/bobojian:${{ github.sha }}
          # 上面的标签表示：同时推送 latest（最新版）和 本次提交的SHA值（唯一标识）
